-- 데이터 조회 필터링 - 10. IS NULL 연산자

-- NULL을 비교할때에는 = 연산자가 아닌 IS 및 IS NOT 연산자를 사용해야 한다.

create table contacts ( ID INT generated by default as identity ,
first_name varchar(50) not null,
last_name varchar(50) not null,
email varchar(225) not null,
phone varchar(15),
primary key(ID) );

insert
	into
	contacts(first_name,
	last_name,
	email,
	phone)
values('John',
'Doe',
'john.doe@eample.com',
null),
('Lily',
'Bush',
'lily.bush@example.com',
'(408-234-2764)')

commit;

---------------------------------------------

select
	id,
	first_name,
	last_name,
	email,
	phone
from
	contacts c
where
	phone is null -- is 가 아닌 = 를 사용하면 안된다.

----------------------------------------------
	
select
	id,
	first_name,
	last_name,
	email,
	phone
from
	contacts c
where
	phone is not null